// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/content-dashboard/CommandDispatch.tsx": () => import("../components/mockups/content-dashboard/CommandDispatch.tsx"),
  "./components/mockups/content-dashboard/LiveOutputGrid.tsx": () => import("../components/mockups/content-dashboard/LiveOutputGrid.tsx"),
  "./components/mockups/content-dashboard/StudioTimeline.tsx": () => import("../components/mockups/content-dashboard/StudioTimeline.tsx")
};
